"""add business fields to orders

Revision ID: 1e7dcf9f14ae
Revises: 77e018c1ec29
Create Date: 2026-02-16 16:30:46.405837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7dcf9f14ae'
down_revision: Union[str, Sequence[str], None] = '77e018c1ec29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('snapshot_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(index_name=op.f('ix_orders_status'), table_name='orders')
    # ### end Alembic commands ###
    op.execute("""
        UPDATE orders
        SET snapshot_price = p.price,
            total_amount = p.price * orders.quantity,
            status = 'paid',
            updated_at = NOW()
        FROM products p
        WHERE orders.product_id = p.id
        """
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'snapshot_price')
    # ### end Alembic commands ###
