"""create index {user_id, order_time} in Order table

Revision ID: 739b5d4da5f1
Revises: ef898edea7ce
Create Date: 2026-03-06 16:24:55.096930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739b5d4da5f1'
down_revision: Union[str, Sequence[str], None] = 'ef898edea7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_orders_user_time', 'orders', ['user_id', 'order_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orders_user_time', table_name='orders')
    # ### end Alembic commands ###
