"""add orders table

Revision ID: 77e018c1ec29
Revises: c41f6ef90208
Create Date: 2026-02-15 14:50:25.234488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e018c1ec29'
down_revision: Union[str, Sequence[str], None] = 'c41f6ef90208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_amount'), 'orders', ['amount'], unique=False)
    op.create_index(op.f('ix_orders_order_time'), 'orders', ['order_time'], unique=False)
    op.create_index(op.f('ix_orders_quantity'), 'orders', ['quantity'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_quantity'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_time'), table_name='orders')
    op.drop_index(op.f('ix_orders_amount'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
